# requirements.yml
---
collections:
  - name: community.general
    version: 3.5.0
  - name: ansible.builtin
    version: 1.1.0
  - name: github_user.github_collection
    src: https://github.com/nobre165/test01.git
    version: master
    type: git
  - name: ibm.power_aix
  - name: ibm.power_aix_sap
  - name: ibm.power_hmc
  - name: ibm.power_aix_oracle_rac_asm
  - name: ibm.power_vios
  - name: ibm.ds8000
  - name: ibm.power_aix_oracle
  - name: ibm.power_linux_sap
  - name: ibm.cloud
