# requirements.yml
---
collections:
  - name: community.general
    version: 3.5.0
  - name: ansible.builtin
    version: 1.1.0
  - name: github_user.github_collection
    src: https://github.com/github_user/github_collection.git
    version: master
    type: git
    client_id: YOUR_GITHUB_CLIENT_ID
    client_secret: YOUR_GITHUB_CLIENT_SECRET
  - name: galaxy_user.galaxy_collection
