# requirements.yml
---
collections:
  - name: community.general
  - name: ibm.power_aix
  - name: ibm.power_aix_sap
  - name: ibm.power_hmc
  - name: ibm.power_aix_oracle_rac_asm
  - name: ibm.power_vios
  - name: ibm.ds8000
  - name: ibm.power_aix_oracle
  - name: ibm.power_linux_sap
  - name: ibm.cloud
  - name: https://github.com/nobre165/mycoll.git
    type: git
    version: main
  - name: git+https://nobre165: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@github.com/nobre165/mycoll02.git
    version: main
